version: '3.9'

services:

  symfony-api:
    container_name: symfony_api
    image: symfony-api/dev
    build:
      context: .
    volumes:
      - .:/app
    restart: unless-stopped
    ports:
      - "8000:8000"
    networks:
      - symfony-bridge-external
